version: '3.3'
name: video-streaming-system
services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - 'project1-apiNetwork'
    environment:
      MYSQL_ROOT_PASSWORD: project1
      MYSQL_DATABASE: project1
      MYSQL_USER: project1
      MYSQL_PASSWORD: project1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3310:3306'
    expose:
      - '3306'
    volumes:
      - project1-db:/var/lib/mysql
  authentication:
    depends_on:
      - db
    image: authentication
    restart: always
    build: ../authentication
    ports:
      - 3004:3004
    expose:
      - '3004'
    networks:
      - 'project1-apiNetwork'
    volumes:
      - ../authentication:/usr/src/app
  client:
    depends_on:
      - authentication
    image: client
    restart: always
    build: ../client
    ports:
      - 4000:3000
    networks:
      - 'project1-apiNetwork'
    volumes:
      - ../client:/usr/src/app
volumes:
  project1-db:
networks:
  project1-apiNetwork:
