version: '3.3'
name: video-streaming-system
services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - 'project1-apiNetwork'
    environment:
      MYSQL_ROOT_PASSWORD: project1
      MYSQL_DATABASE: project1
      MYSQL_USER: project1
      MYSQL_PASSWORD: project1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - project1-db:/var/lib/mysql

  authentication:
    depends_on:
      - db
    image: authentication:latest
    restart: always
    build: ../authentication
    # Ports that will be exposed to the host
    # ports:
    #   - 3004:3004
    networks:
      - 'project1-apiNetwork'

  file_system:
    depends_on:
      - db
    image: file_system:latest
    restart: always
    build: ../file_system
    # ports:
    #   - 3010:3010
    networks:
      - 'project1-apiNetwork'
    volumes:
      - project1-uploads:/app/public/videos

  nginx:
    depends_on:
      - authentication
      - file_system
    image: nginx:latest
    ports:
      - 4010:80
    networks:
      - 'project1-apiNetwork'
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf

  client:
    depends_on:
      - authentication
      - file_system
      - nginx
    image: client:latest
    restart: always
    build: ../client
    ports:
      - 4000:3000
    networks:
      - 'project1-apiNetwork'
    volumes:
      - project1-uploads:/app/public/videos

  upload_video:
    depends_on:
      - authentication
      - nginx
    image: upload_video:latest
    restart: always
    build: ../upload_video
    ports:
      - 4004:3000
    networks:
      - 'project1-apiNetwork'

volumes:
  project1-db:
  project1-uploads:
networks:
  project1-apiNetwork:
