version: '3.3'
name: video-streaming-system
services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - 'project1-apiNetwork'
    environment:
      MYSQL_ROOT_PASSWORD: project1
      MYSQL_DATABASE: project1
      MYSQL_USER: project1
      MYSQL_PASSWORD: project1
    volumes:
      - project1-db:/var/lib/mysql

  authentication:
    depends_on:
      - db
    image: phamminhtan2k2/video-streaming-authentication:v1
    restart: always
    networks:
      - 'project1-apiNetwork'

  file_system:
    depends_on:
      - db
    image: phamminhtan2k2/video-streaming-file:v1
    restart: always
    networks:
      - 'project1-apiNetwork'
    volumes:
      - project1-uploads:/app/public/videos

  nginx:
    depends_on:
      - authentication
      - file_system
    image: phamminhtan2k2/video-streaming-nginx:v1
    ports:
      - 4010:80
    networks:
      - 'project1-apiNetwork'

  client:
    depends_on:
      - authentication
      - file_system
      - nginx
    image: phamminhtan2k2/video-streaming-client:v1
    restart: always
    ports:
      - 4000:3000
    networks:
      - 'project1-apiNetwork'
    volumes:
      - project1-uploads:/app/public/videos

  upload_video:
    depends_on:
      - authentication
      - nginx
    image: phamminhtan2k2/video-streaming-uploads:v1
    restart: always
    ports:
      - 4004:3000
    networks:
      - 'project1-apiNetwork'

volumes:
  project1-db:
  project1-uploads:
networks:
  project1-apiNetwork:
